name: License Header Check
on: [push, pull_request]

jobs:
  check-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify Headers
        run: |
          grep -L "AGPL-3.0 License" $(find src -name '*.tsx') && exit 1 || exit 0 